'use client';

import React, { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

export default function AnalyticsDashboardPage() {
  const supabase = createClient();
  const [loading, setLoading] = useState(true);
  
  // المؤشرات الأساسية
  const [stats, setStats] = useState({
    totalRequests: 0,
    sentQuotes: 0,
    acceptedQuotes: 0,
    totalBookings: 0,
    totalRevenue: 0,
    avgBookingValue: 0,
    conversionRate: '0%', // النسبة العامة للتحويل
    reqToQuoteRate: '0%', // نسبة تحول الطلب إلى عرض
    quoteToBookingRate: '0%', // نسبة تحول العرض إلى حجز
  });

  // مؤشرات "قيمة النظام" (الذكية)
  const [systemValue, setSystemValue] = useState({
    autoProcessedRequests: 0,
    outOfHoursRequests: 0,
    autoGeneratedQuotes: 0,
    autoRevenue: 0,
  });

  useEffect(() => {
    async function loadAnalytics() {
      // 1. جلب بيانات الشركة الحالية
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      const { data: userData } = await supabase.from('company_users').select('company_id').eq('id', user.id).single();
      if (!userData) return;
      
      const companyId = userData.company_id;

      // 2. جلب جميع الطلبات، العروض، والحجوزات (المعزولة للشركة)
      const { data: requests } = await supabase.from('quote_requests').select('id, created_at, status').eq('company_id', companyId);
      const { data: quotes } = await supabase.from('quotes').select('id, created_at, status, total_amount').eq('company_id', companyId);
      const { data: bookings } = await supabase.from('bookings').select('id, total_price, created_at').eq('company_id', companyId);

      const reqCount = requests?.length || 0;
      const quoteCount = quotes?.length || 0;
      const acceptedQuotesCount = quotes?.filter(q => q.status === 'accepted').length || 0;
      const bookingCount = bookings?.length || 0;
      
      const revenue = bookings?.reduce((sum, item) => sum + Number(item.total_price || 0), 0) || 0;

      // حساب نسب التحويل
      const reqToQuote = reqCount > 0 ? ((quoteCount / reqCount) * 100).toFixed(1) : '0';
      const quoteToBooking = quoteCount > 0 ? ((bookingCount / quoteCount) * 100).toFixed(1) : '0';
      const overallConversion = reqCount > 0 ? ((bookingCount / reqCount) * 100).toFixed(1) : '0';
      const avgValue = bookingCount > 0 ? Math.round(revenue / bookingCount) : 0;

      setStats({
        totalRequests: reqCount,
        sentQuotes: quoteCount,
        acceptedQuotes: acceptedQuotesCount,
        totalBookings: bookingCount,
        totalRevenue: revenue,
        avgBookingValue: avgValue,
        conversionRate: `${overallConversion}%`,
        reqToQuoteRate: `${reqToQuote}%`,
        quoteToBookingRate: `${quoteToBooking}%`
      });

      // 3. حساب "قيمة النظام" (أوقات العمل والأتمتة)
      // تعريف أوقات خارج العمل (مثلاً: قبل 8 صباحاً وبعد 6 مساءً)
      let outOfHours = 0;
      requests?.forEach(req => {
        const hour = new Date(req.created_at).getHours();
        if (hour < 8 || hour > 18) outOfHours++;
      });

      // في نظامنا الحالي، كل العروض تصدر تلقائياً بمجرد إرسال الطلب (Auto-Quotes)
      setSystemValue({
        autoProcessedRequests: reqCount, // النظام يعالجها فوراً
        outOfHoursRequests: outOfHours,
        autoGeneratedQuotes: quoteCount,
        autoRevenue: revenue // كل الحجوزات جاءت من أتمتة النظام
      });

      setLoading(false);
    }
    loadAnalytics();
  }, []);

  if (loading) {
    return <div className="min-h-screen flex items-center justify-center font-bold text-gray-500">جاري حساب تحليلات النظام...</div>;
  }

  // بطاقات المؤشرات الأساسية
  const mainStatsCards = [
    { label: 'إجمالي الطلبات', value: stats.totalRequests, icon: '📥' },
    { label: 'العروض المُرسلة', value: stats.sentQuotes, icon: '📄' },
    { label: 'العروض المقبولة', value: stats.acceptedQuotes, icon: '✅' },
    { label: 'إجمالي الحجوزات', value: stats.totalBookings, icon: '📅' },
    { label: 'متوسط قيمة الحجز', value: `${stats.avgBookingValue} ﷼`, icon: '📊' },
    { label: 'القيمة الإجمالية', value: `${stats.totalRevenue.toLocaleString()} ﷼`, icon: '💰', highlight: true },
  ];

  // بطاقات معدلات التحويل
  const conversionCards = [
    { label: 'نسبة الإغلاق (Conversion)', value: stats.conversionRate, desc: 'من الطلب إلى الحجز' },
    { label: 'معدل إصدار العروض', value: stats.reqToQuoteRate, desc: 'الطلبات التي تحولت لعروض' },
    { label: 'معدل قبول العروض', value: stats.quoteToBookingRate, desc: 'العروض التي تحولت لحجوزات' },
  ];

  // بطاقات قيمة النظام (ROI)
  const systemValueCards = [
    { label: 'طلبات عُولجت تلقائياً', value: systemValue.autoProcessedRequests, desc: 'بدون تدخل بشري' },
    { label: 'طلبات خارج أوقات العمل', value: systemValue.outOfHoursRequests, desc: 'عملاء تم خدمتهم بعد الدوام' },
    { label: 'عروض أُصدرت فورياً', value: systemValue.autoGeneratedQuotes, desc: 'تسعير ديناميكي سريع' },
    { label: 'أرباح من الأتمتة', value: `${systemValue.autoRevenue.toLocaleString()} ﷼`, desc: 'إجمالي العوائد عبر النظام' },
  ];

  return (
    <div className="p-6 md:p-10 bg-[#f4f6f8] min-h-screen" dir="rtl">
      
      <div className="mb-10">
        <h1 className="text-3xl font-extrabold text-gray-900 mb-2">التحليلات والأداء 📈</h1>
        <p className="text-gray-500">نظرة شاملة ومبنية على بيانات حقيقية لأداء شركتك.</p>
      </div>

      {/* 1. المؤشرات الأساسية */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-10">
        {mainStatsCards.map((card, i) => (
          <div key={i} className={`p-6 rounded-2xl shadow-sm border ${card.highlight ? 'bg-gray-900 text-white border-gray-800' : 'bg-white border-gray-100'}`}>
            <div className="text-2xl mb-2">{card.icon}</div>
            <p className={`text-xs font-bold mb-1 ${card.highlight ? 'text-gray-400' : 'text-gray-500'}`}>{card.label}</p>
            <h3 className={`text-2xl font-extrabold ${card.highlight ? 'text-[#b89742]' : 'text-gray-900'}`}>{card.value}</h3>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-10">
        {/* 2. معدلات التحويل */}
        <div className="lg:col-span-1 bg-white p-6 rounded-3xl shadow-sm border border-gray-100">
          <h2 className="text-xl font-bold text-gray-900 mb-6 flex items-center gap-2"><span>🎯</span> معدلات التحويل</h2>
          <div className="space-y-6">
            {conversionCards.map((card, i) => (
              <div key={i} className="pb-4 border-b border-gray-50 last:border-0 last:pb-0">
                <div className="flex justify-between items-end mb-1">
                  <span className="text-sm font-bold text-gray-600">{card.label}</span>
                  <span className="text-xl font-extrabold text-blue-600">{card.value}</span>
                </div>
                <p className="text-xs text-gray-400">{card.desc}</p>
                {/* شريط تقدم وهمي بصرياً بناء على النسبة */}
                <div className="w-full bg-gray-100 rounded-full h-1.5 mt-2">
                  <div className="bg-blue-500 h-1.5 rounded-full" style={{ width: card.value }}></div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* 3. قيمة النظام (الذكاء الاصطناعي والأتمتة) */}
        <div className="lg:col-span-2 bg-gradient-to-br from-[#1a1c23] to-[#2d3748] p-8 rounded-3xl shadow-lg border border-gray-800 text-white relative overflow-hidden">
          {/* تأثير بصري */}
          <div className="absolute -top-24 -left-24 w-64 h-64 bg-[#b89742] rounded-full opacity-10 blur-3xl"></div>
          
          <h2 className="text-2xl font-bold mb-8 flex items-center gap-2 relative z-10"><span>⚡</span> القيمة المضافة للنظام (ROI)</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 relative z-10">
            {systemValueCards.map((card, i) => (
              <div key={i} className="bg-white/5 p-6 rounded-2xl border border-white/10 backdrop-blur-sm hover:bg-white/10 transition-colors">
                <p className="text-gray-400 text-sm font-medium mb-2">{card.label}</p>
                <h3 className="text-3xl font-extrabold text-white mb-1">{card.value}</h3>
                <p className="text-xs text-[#b89742] font-bold">{card.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 4. مساحة الرسوم الزمنية (مؤقتاً نعرض رسالة لعدم وجود مكتبة Charts جاهزة) */}
      <div className="bg-white p-8 rounded-3xl shadow-sm border border-gray-100 flex flex-col items-center justify-center min-h-[300px] text-center">
        <span className="text-5xl mb-4">📊</span>
        <h3 className="text-xl font-bold text-gray-900 mb-2">المخططات الزمنية (يومي، أسبوعي، شهري)</h3>
        <p className="text-gray-500 max-w-md">البيانات جاهزة في الخادم. لدمج الرسوم البيانية التفاعلية، نحتاج لتثبيت مكتبة متخصصة مثل <code>Recharts</code> في مشروعك. هل ترغب في إضافتها في الخطوات القادمة؟</p>
      </div>

    </div>
  );
}